services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82
            - mysql8
            - redis
        networks:
            - ranghis
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - ranghis
    php82:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php82
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - ranghis
    mysql8:
        image: mysql:8
        container_name: mysql8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - ranghis
networks:
    ranghis:
        name: nginx-php82-mysql8-redis